name: fix-code-style

on:
  push:

jobs:
  fix-code-style:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        php: [8.3]
        laravel: [10.*]
        dependency-version: [prefer-stable]
        include:
          - laravel: 10.*
            testbench: 8.*
        exclude:
          - laravel: 10.*
            php: '8.3'
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.head_ref }}
      - name: Set up Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest
      - name: Install dependencies
        run: |
          sudo add-apt-repository -y ppa:ondrej/php
          sudo apt-get update
          sudo apt-get install -y php${{ matrix.php }}
          sudo update-alternatives --set php /usr/bin/php${{ matrix.php }}
          composer install --no-interaction
          bun install
      - name: Run Pint
        run: ./vendor/bin/pint
      - name: Run Prettier
        run: bun x prettier --write .
      - name: Pull changes
        run: git pull
      - name: Commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: 'chore: fix code style'
